### ISSUE TITLE
extract wallets history transaction 

### ISSUE THREAD

**Issue by stefi-says** [OpenDataforWeb3/GIS#9]
Get the historical wallets transactions for the wallets, and get the historical transactions for the walletes that they transacted with and so  in a degree that we need to determine ( 10 layers, 20 layers?)

Probably we will use covalent to do so , so this issue depends on the issue #5

**Comment by epowell101** [comment]
Closing this as we have the transaction history for the labeled EOAs thanks to @poupou-web3
